name: Trademark removal request
description: For rights-holders requesting that a logo be removed
labels: ["removal-request"]
body:
  - type: input
    id: project
    attributes:
      label: Project / brand name
    validations:
      required: true
  - type: input
    id: logo-id
    attributes:
      label: iconsol logo id (e.g. "phantom")
    validations:
      required: true
  - type: input
    id: capacity
    attributes:
      label: Your relationship to the brand (employee, counsel, etc.)
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      label: Reason for removal
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact email for verification
    validations:
      required: true
