/**
 * generate-components.ts
 *
 * Converts SVG files in icons/ into React TypeScript components
 * and writes them to packages/react/src/icons/
 *
 * Run: pnpm generate
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { transform } from "@svgr/core";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const ICONS_DIR = path.join(ROOT, "icons");
const OUTPUT_DIR = path.join(ROOT, "packages", "react", "src", "icons");
const MANIFEST_PATH = path.join(ICONS_DIR, "manifest.json");

interface ManifestEntry {
  id: string;
  name: string;
  category: string;
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

// Minimal SVG normalization before passing to SVGR
function normalizeSvg(svgContent: string): string {
  // Remove XML declaration and doctype
  let svg = svgContent.replace(/<\?xml[^>]*\?>/gi, "").trim();
  svg = svg.replace(/<!DOCTYPE[^>]*>/gi, "").trim();
  // Remove comments
  svg = svg.replace(/<!--[\s\S]*?-->/g, "");
  return svg;
}

async function svgToReactComponent(
  svgContent: string,
  componentName: string
): Promise<string> {
  const normalized = normalizeSvg(svgContent);
  const generated = await transform(
    normalized,
    {
      plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx", "@svgr/plugin-prettier"],
      svgoConfig: {
        plugins: [{ name: "preset-default" }, { name: "removeDimensions" }],
      },
      typescript: true,
      ref: false,
      titleProp: false,
      expandProps: "end",
      icon: true,
    },
    { componentName }
  );

  const jsx = generated
    .replace(/^import \* as React from "react";\n/m, "")
    .replace(/^import type { SVGProps } from "react";\n/m, "")
    .replace(
      new RegExp(`const ${componentName} = \\(props: SVGProps<SVGSVGElement>\\) => `),
      ""
    )
    .replace(new RegExp(`\nexport default ${componentName};\\s*$`), "")
    .replace(/width="1em"/, "width={size}")
    .replace(/height="1em"/, "height={size}")
    .trim()
    .replace(/;$/, "");

  return `import type { SVGProps } from "react";

export interface ${componentName}Props extends SVGProps<SVGSVGElement> {
  size?: number | string;
}

export function ${componentName}({
  size = 24,
  ...props
}: ${componentName}Props) {
  return ${jsx};
}

export default ${componentName};
`;
}

async function main() {
  console.log("\n⚙️  Solana Icons Component Generator\n");

  const manifest: ManifestEntry[] = JSON.parse(
    fs.readFileSync(MANIFEST_PATH, "utf8")
  );

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const generated: Array<{ id: string; componentName: string; category: string }> = [];
  const skipped: string[] = [];

  for (const entry of manifest) {
    const categoryDir = path.join(ICONS_DIR, entry.category);
    const svgPath = path.join(categoryDir, `${entry.id}.svg`);
    const pngPath = path.join(categoryDir, `${entry.id}.png`);

    // Only process SVGs (PNGs are exported as-is, not as React components)
    if (!fs.existsSync(svgPath)) {
      if (fs.existsSync(pngPath)) {
        console.log(`   ⚠ ${entry.id} — PNG only, skipping component generation`);
      } else {
        console.log(`   ✗ ${entry.id} — no icon file found`);
      }
      skipped.push(entry.id);
      continue;
    }

    const componentName = toPascalCase(entry.id);
    const svgContent = fs.readFileSync(svgPath, "utf8");

    try {
      const component = await svgToReactComponent(svgContent, componentName);
      const outPath = path.join(OUTPUT_DIR, `${componentName}.tsx`);
      fs.writeFileSync(outPath, component);
      console.log(`   ✓ ${componentName}`);
      generated.push({ id: entry.id, componentName, category: entry.category });
    } catch (err) {
      console.error(`   ✗ ${entry.id} — error:`, err);
      skipped.push(entry.id);
    }
  }

  // Generate index.ts with all exports
  const indexLines = [
    `// Auto-generated by scripts/generate-components.ts`,
    `// Do not edit manually — run \`pnpm generate\``,
    ``,
    ...generated.map(
      ({ componentName }) =>
        `export { ${componentName}, type ${componentName}Props } from "./icons/${componentName}";`
    ),
    ``,
    `// Re-export icon metadata`,
    `export type { IconEntry } from "./types";`,
    ``,
  ];

  fs.writeFileSync(
    path.join(ROOT, "packages", "react", "src", "index.ts"),
    indexLines.join("\n")
  );

  // Generate types.ts
  const typesContent = `// Icon manifest type
export interface IconEntry {
  id: string;
  name: string;
  ticker?: string;
  category: "tokens" | "defi" | "wallets" | "nft" | "infrastructure";
  aliases?: string[];
  tags?: string[];
  mintAddress?: string;
  website?: string;
}
`;
  fs.writeFileSync(
    path.join(ROOT, "packages", "react", "src", "types.ts"),
    typesContent
  );

  console.log(`\n✅ Generated ${generated.length} components, skipped ${skipped.length}`);
  console.log(`   Output: packages/react/src/\n`);
}

main().catch(console.error);
