// AUTO-GENERATED by tools/icons/build.ts — DO NOT EDIT.
// Run `pnpm icons:build` to regenerate.
// Kept separate from logo-assets.ts so pages that only need the count
// don't pull the full asset data into their client bundle.
export const ICON_COUNT = 59;
