/* eslint-disable */
// AUTO-GENERATED by tools/icons/build.ts — DO NOT EDIT.
// Source of truth: icons/<id>/icon.json. Run `pnpm icons:build` to regenerate.

import type { IconCategory, Contributor } from "./icon-data";

export type LogoId =
  | "sol"
  | "sanctum"
  | "helius"
  | "jup"
  | "phantom"
  | "helius-orb"
  | "backpack"
  | "solflare"
  | "sanctum-gateway"
  | "perena"
  | "superteam"
  | "carrot"
  | "oro"
  | "altitude"
  | "dflow"
  | "pump-fun"
  | "usd-prime"
  | "fuse"
  | "usd-star"
  | "xstock"
  | "magic-eden"
  | "colosseum"
  | "scloud"
  | "crossmint"
  | "marginfi"
  | "kamino"
  | "infsol"
  | "moonshot"
  | "umbra"
  | "arcium"
  | "bonk"
  | "kast"
  | "asgard"
  | "fomo"
  | "jupiter-lend"
  | "moonpay"
  | "jto"
  | "sendai"
  | "eurc"
  | "usdc"
  | "circle"
  | "bags"
  | "powered-by-solana"
  | "jupusd"
  | "jitosol"
  | "madlads"
  | "opos"
  | "drip-haus"
  | "jupsol"
  | "metadao"
  | "meteora"
  | "jito"
  | "marinade"
  | "metaplex"
  | "raydium"
  | "zora"
  | "claynosaurz"
  | "seeker"
  | "avici"
  | "squads"
  | "usdt";

export interface LogoAssetLayer {
  src: string;
  width: number;
  height: number;
  x: number;
  y: number;
  rotation?: number;
  maskSrcs?: string[];
  maskPositions?: string;
  maskSizes?: string;
}

export interface LogoAssetSpec {
  background?: string;
  radius?: number;
  layers: LogoAssetLayer[];
}

export type LogoVariant = "brand" | "solid";

export const LOGO_ORDER: LogoId[] = [
  "sol",
  "sanctum",
  "helius",
  "jup",
  "phantom",
  "helius-orb",
  "backpack",
  "solflare",
  "sanctum-gateway",
  "perena",
  "superteam",
  "carrot",
  "oro",
  "altitude",
  "dflow",
  "pump-fun",
  "usd-prime",
  "fuse",
  "usd-star",
  "xstock",
  "magic-eden",
  "colosseum",
  "scloud",
  "crossmint",
  "marginfi",
  "kamino",
  "infsol",
  "moonshot",
  "umbra",
  "arcium",
  "bonk",
  "kast",
  "asgard",
  "fomo",
  "jupiter-lend",
  "moonpay",
  "jto",
  "sendai",
  "eurc",
  "usdc",
  "circle",
  "bags",
  "powered-by-solana",
  "jupusd",
  "jitosol",
  "madlads",
  "opos",
  "drip-haus",
  "jupsol",
  "metadao",
  "meteora",
  "jito",
  "marinade",
  "metaplex",
  "raydium",
  "zora",
  "claynosaurz",
  "seeker",
  "avici",
  "squads",
  "usdt",
];

export const BRAND_LOGO_ASSETS: Record<LogoId, LogoAssetSpec> = {
  sol: {
    layers: [
      { src: "/brand/sol.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  sanctum: {
    layers: [
      { src: "/brand/sanctum.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  helius: {
    layers: [
      { src: "/brand/helius.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  jup: {
    layers: [
      { src: "/brand/jup.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  phantom: {
    layers: [
      { src: "/brand/phantom.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "helius-orb": {
    layers: [
      { src: "/brand/helius-orb.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  backpack: {
    background: "#e33e3f",
    radius: 8,
    layers: [
      { src: "/brand/backpack.svg", x: 9.1145, y: 6.0125, width: 13.771, height: 19.975 },
    ],
  },
  solflare: {
    background: "#ffef46",
    radius: 8,
    layers: [
      { src: "/brand/solflare-fill.svg", x: 6.6045, y: 6.0215, width: 18.791, height: 19.957, maskSrcs: ["/brand/solflare-mask.svg"] },
    ],
  },
  "sanctum-gateway": {
    layers: [
      { src: "/brand/sanctum-gateway.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  perena: {
    layers: [
      { src: "/brand/perena.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  superteam: {
    layers: [
      { src: "/brand/superteam.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  carrot: {
    background: "#022c22",
    radius: 8,
    layers: [
      { src: "/brand/carrot.svg", x: 5.9990000000000006, y: 5.9990000000000006, width: 20.002, height: 20.002 },
    ],
  },
  oro: {
    layers: [
      { src: "/brand/oro.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  altitude: {
    layers: [
      { src: "/brand/altitude.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  dflow: {
    layers: [
      { src: "/brand/dflow.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "pump-fun": {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/pump-fun.svg", x: 6, y: 5.697, width: 19.995, height: 20.606 },
    ],
  },
  "usd-prime": {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/usd-prime.svg", x: 2.02, y: 2.01, width: 27.976, height: 27.976 },
    ],
  },
  fuse: {
    background: "#ffffff",
    radius: 8,
    layers: [
      { src: "/brand/fuse.svg", x: 6.0205, y: 6.160500000000001, width: 19.959, height: 19.679 },
    ],
  },
  "usd-star": {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/usd-star.svg", x: 2.01, y: 1.99, width: 27.987, height: 28.021 },
    ],
  },
  xstock: {
    layers: [
      { src: "/brand/xstock.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "magic-eden": {
    layers: [
      { src: "/brand/magic-eden.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  colosseum: {
    layers: [
      { src: "/brand/colosseum.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  scloud: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/scloud.svg", x: 2.0039999999999996, y: 2.2295, width: 27.992, height: 27.541 },
    ],
  },
  crossmint: {
    layers: [
      { src: "/brand/crossmint.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  marginfi: {
    layers: [
      { src: "/brand/marginfi.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  kamino: {
    layers: [
      { src: "/brand/kamino.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  infsol: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/infsol-left.svg", x: 5.9285, y: 10.1143, width: 11.771, height: 11.771 },
      { src: "/brand/infsol-right.svg", x: 14.2515, y: 10.1143, width: 11.771, height: 11.771 },
      { src: "/brand/infsol-center.svg", x: 13.0575, y: 13.0575, width: 5.885, height: 5.885, rotation: 45 },
    ],
  },
  moonshot: {
    layers: [
      { src: "/brand/moonshot.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  umbra: {
    layers: [
      { src: "/brand/umbra.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  arcium: {
    background: "#6d45ff",
    radius: 8,
    layers: [
      { src: "/brand/arcium.svg", x: 4.960000000000001, y: 8.0055, width: 22.08, height: 15.989 },
    ],
  },
  bonk: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/bonk.svg", x: 2, y: 2, width: 28, height: 28 },
    ],
  },
  kast: {
    layers: [
      { src: "/brand/kast.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  asgard: {
    layers: [
      { src: "/brand/asgard.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  fomo: {
    layers: [
      { src: "/brand/fomo.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "jupiter-lend": {
    layers: [
      { src: "/brand/jupiter-lend.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  moonpay: {
    layers: [
      { src: "/brand/moonpay.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  jto: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/jto.svg", x: 2, y: 2, width: 28, height: 28 },
    ],
  },
  sendai: {
    layers: [
      { src: "/brand/sendai.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  eurc: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/eurc.svg", x: 2, y: 2, width: 28, height: 28 },
    ],
  },
  usdc: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/usdc.svg", x: 2, y: 2, width: 28, height: 28 },
    ],
  },
  circle: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/circle.svg", x: 6.0015, y: 6.0015, width: 19.997, height: 19.997 },
    ],
  },
  bags: {
    layers: [
      { src: "/brand/bags.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "powered-by-solana": {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/powered-by-solana.svg", x: 2.0020000000000007, y: 11.6325, width: 27.996, height: 8.735 },
    ],
  },
  jupusd: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/jupusd.svg", x: 2, y: 2, width: 27.996, height: 27.996 },
    ],
  },
  jitosol: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/jitosol.svg", x: 2, y: 2, width: 28, height: 28 },
    ],
  },
  madlads: {
    layers: [
      { src: "/brand/madlads.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  opos: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/opos.svg", x: 2.0020000000000007, y: 10.2575, width: 27.996, height: 11.485 },
    ],
  },
  "drip-haus": {
    layers: [
      { src: "/brand/drip-haus.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  jupsol: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/jupsol.svg", x: 2, y: 2.03, width: 27.992, height: 27.992 },
    ],
  },
  metadao: {
    layers: [
      { src: "/brand/metadao.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  meteora: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/meteora.svg", x: 6.773, y: 6.004, width: 18.454, height: 19.992 },
    ],
  },
  jito: {
    background: "#3a7861",
    radius: 8,
    layers: [
      { src: "/brand/jito.svg", x: 5.997999999999999, y: 11.8865, width: 20.004, height: 8.227 },
    ],
  },
  marinade: {
    background: "#0b9890",
    radius: 8,
    layers: [
      { src: "/brand/marinade.svg", x: 6.002000000000001, y: 9.236, width: 19.996, height: 13.528 },
    ],
  },
  metaplex: {
    layers: [
      { src: "/brand/metaplex.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  raydium: {
    layers: [
      { src: "/brand/raydium.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  zora: {
    layers: [
      { src: "/brand/zora.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  claynosaurz: {
    background: "linear-gradient(180deg, #fc956c 0%, #ec725b 100%)",
    radius: 8,
    layers: [
      { src: "/brand/claynosaurz.svg", x: 6.004, y: 6.628500000000001, width: 19.992, height: 18.743 },
    ],
  },
  seeker: {
    background: "linear-gradient(180deg, #000000 32.982%, #125d74 61.607%, #85cbc1 90.231%)",
    radius: 8,
    layers: [
      { src: "/brand/seeker.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  avici: {
    background: "#ffffff",
    radius: 8,
    layers: [
      { src: "/brand/avici.svg", x: 6.003500000000001, y: 6.7490000000000006, width: 19.993, height: 18.502 },
    ],
  },
  squads: {
    layers: [
      { src: "/brand/squads.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  usdt: {
    background: "#1a1a1a",
    radius: 8,
    layers: [
      { src: "/brand/usdt.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
};

export const SOLID_LOGO_ASSETS: Record<LogoId, LogoAssetSpec> = {
  sol: {
    layers: [
      { src: "/solid/sol.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  sanctum: {
    layers: [
      { src: "/solid/sanctum.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  helius: {
    layers: [
      { src: "/solid/helius.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  jup: {
    layers: [
      { src: "/solid/jup.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  phantom: {
    layers: [
      { src: "/solid/phantom.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "helius-orb": {
    layers: [
      { src: "/solid/helius-orb.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  backpack: {
    layers: [
      { src: "/solid/backpack.svg", x: 7.0753, y: 3.0542, width: 17.85, height: 25.892 },
    ],
  },
  solflare: {
    layers: [
      { src: "/solid/solflare-fill.svg", x: 3.7744999999999997, y: 3.016, width: 24.451, height: 25.968, maskSrcs: ["/solid/solflare-mask.svg"] },
    ],
  },
  "sanctum-gateway": {
    layers: [
      { src: "/solid/sanctum-gateway.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  perena: {
    layers: [
      { src: "/solid/perena.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  superteam: {
    layers: [
      { src: "/solid/superteam.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  carrot: {
    layers: [
      { src: "/solid/carrot.svg", x: 3, y: 3, width: 26, height: 26 },
    ],
  },
  oro: {
    layers: [
      { src: "/solid/oro.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  altitude: {
    layers: [
      { src: "/solid/altitude.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  dflow: {
    layers: [
      { src: "/solid/dflow.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "pump-fun": {
    layers: [
      { src: "/solid/pump-fun.svg", x: 1.9990000000000006, y: 1.5715000000000003, width: 28.002, height: 28.857 },
    ],
  },
  "usd-prime": {
    layers: [
      { src: "/solid/usd-prime.svg", x: 2.02, y: 2.01, width: 27.976, height: 27.976 },
    ],
  },
  fuse: {
    layers: [
      { src: "/solid/fuse.svg", x: 2.0075000000000003, y: 2.2029999999999994, width: 27.985, height: 27.594 },
    ],
  },
  "usd-star": {
    layers: [
      { src: "/solid/usd-star.svg", x: 2.01, y: 1.99, width: 27.987, height: 28.021 },
    ],
  },
  xstock: {
    layers: [
      { src: "/solid/xstock.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "magic-eden": {
    layers: [
      { src: "/solid/magic-eden.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  colosseum: {
    layers: [
      { src: "/solid/colosseum.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  scloud: {
    layers: [
      { src: "/solid/scloud.svg", x: 2.0039999999999996, y: 2.2295, width: 27.992, height: 27.541 },
    ],
  },
  crossmint: {
    layers: [
      { src: "/solid/crossmint.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  marginfi: {
    layers: [
      { src: "/solid/marginfi.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  kamino: {
    layers: [
      { src: "/solid/kamino.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  infsol: {
    layers: [
      { src: "/solid/infsol.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  moonshot: {
    layers: [
      { src: "/solid/moonshot.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  umbra: {
    layers: [
      { src: "/solid/umbra.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  arcium: {
    layers: [
      { src: "/solid/arcium.svg", x: 3.3149999999999995, y: 6.814, width: 25.37, height: 18.372 },
    ],
  },
  bonk: {
    layers: [
      { src: "/solid/bonk.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  kast: {
    layers: [
      { src: "/solid/kast.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  asgard: {
    layers: [
      { src: "/solid/asgard.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  fomo: {
    layers: [
      { src: "/solid/fomo.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "jupiter-lend": {
    layers: [
      { src: "/solid/jupiter-lend.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  moonpay: {
    layers: [
      { src: "/solid/moonpay.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  jto: {
    layers: [
      { src: "/solid/jto.svg", x: 2, y: 2, width: 28, height: 28 },
    ],
  },
  sendai: {
    layers: [
      { src: "/solid/sendai.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  eurc: {
    layers: [
      { src: "/solid/eurc.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  usdc: {
    layers: [
      { src: "/solid/usdc.svg", x: 2.02, y: 2.43, width: 27.961, height: 27.146 },
    ],
  },
  circle: {
    layers: [
      { src: "/solid/circle.svg", x: 2.01, y: 2.03, width: 27.953, height: 27.953 },
    ],
  },
  bags: {
    layers: [
      { src: "/solid/bags.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  "powered-by-solana": {
    layers: [
      { src: "/solid/powered-by-solana.svg", x: 2.0020000000000007, y: 11.6325, width: 27.996, height: 8.735 },
    ],
  },
  jupusd: {
    layers: [
      { src: "/solid/jupusd.svg", x: 3.4, y: 3.41, width: 25.172, height: 25.173 },
    ],
  },
  jitosol: {
    layers: [
      { src: "/solid/jitosol.svg", x: 2, y: 2, width: 28, height: 28 },
    ],
  },
  madlads: {
    layers: [
      { src: "/solid/madlads-fill.svg", x: 2.0045, y: 2.0045, width: 27.991, height: 27.991, maskSrcs: ["/solid/madlads-mask-a.svg", "/solid/madlads-mask-b.svg"], maskPositions: "0px 0px, -0.026px -0.003px", maskSizes: "100% 100%, 100% 100%" },
    ],
  },
  opos: {
    layers: [
      { src: "/solid/opos.svg", x: 2.0020000000000007, y: 10.2575, width: 27.996, height: 11.485 },
    ],
  },
  "drip-haus": {
    layers: [
      { src: "/solid/drip-haus.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  jupsol: {
    layers: [
      { src: "/solid/jupsol.svg", x: 2, y: 2.03, width: 27.992, height: 27.992 },
    ],
  },
  metadao: {
    layers: [
      { src: "/solid/metadao-fill.svg", x: 4.7885, y: 4.7885, width: 22.423, height: 22.423, maskSrcs: ["/solid/metadao-mask.svg"], maskSizes: "100% 100%" },
    ],
  },
  meteora: {
    layers: [
      { src: "/solid/meteora.svg", x: 3.231, y: 2.167, width: 25.538, height: 27.666 },
    ],
  },
  jito: {
    layers: [
      { src: "/solid/jito.svg", x: 2, y: 10.77, width: 27.996, height: 11.514 },
    ],
  },
  marinade: {
    layers: [
      { src: "/solid/marinade.svg", x: 2, y: 6.528499999999999, width: 28, height: 18.943 },
    ],
  },
  metaplex: {
    layers: [
      { src: "/solid/metaplex.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  raydium: {
    layers: [
      { src: "/solid/raydium.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  zora: {
    layers: [
      { src: "/solid/zora.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  claynosaurz: {
    layers: [
      { src: "/solid/claynosaurz.svg", x: 2.0045, y: 2.8795, width: 27.991, height: 26.241 },
    ],
  },
  seeker: {
    layers: [
      { src: "/solid/seeker.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  avici: {
    layers: [
      { src: "/solid/avici.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  squads: {
    layers: [
      { src: "/solid/squads.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
  usdt: {
    layers: [
      { src: "/solid/usdt.svg", x: 0, y: 0, width: 32, height: 32 },
    ],
  },
};

export interface IconMeta {
  id: string;
  name: string;
  ticker?: string;
  category: IconCategory;
  aliases: string[];
  tags: string[];
  website?: string;
  twitter?: string;
  github?: string;
  mintAddress?: string;
  description?: string;
  relatedIds?: string[];
  contributors?: Contributor[];
  hasDisplay: boolean;
}

export const ICON_META: Record<string, IconMeta> = {
  sol: {
    "id": "sol",
    "name": "Solana",
    "category": "tokens",
    "aliases": [
      "solana",
      "sol"
    ],
    "tags": [
      "native",
      "gas",
      "staking"
    ],
    "ticker": "SOL",
    "website": "https://solana.com",
    "mintAddress": "So11111111111111111111111111111111111111112",
    "description": "Solana is a high-performance layer 1 network powering online capital markets, payments, and cryptocurrency applications.",
    "relatedIds": [
      "jup",
      "usdc",
      "jitosol",
      "jupsol"
    ],
    "hasDisplay": true
  },
  sanctum: {
    "id": "sanctum",
    "name": "Sanctum",
    "category": "defi",
    "aliases": [
      "sanctum"
    ],
    "tags": [
      "liquid-staking"
    ],
    "website": "https://sanctum.so",
    "description": "Sanctum is a Solana liquid staking infrastructure protocol unifying LSTs into a single, interoperable staking economy.",
    "relatedIds": [
      "infsol",
      "scloud",
      "jitosol",
      "marinade"
    ],
    "hasDisplay": true
  },
  helius: {
    "id": "helius",
    "name": "Helius",
    "category": "infrastructure",
    "aliases": [
      "helius"
    ],
    "tags": [
      "rpc",
      "api",
      "developer"
    ],
    "website": "https://helius.dev",
    "description": "Helius provides Solana developer infrastructure for RPC, indexing, webhooks, and real-time data delivery at scale.",
    "relatedIds": [
      "sol",
      "jup",
      "phantom"
    ],
    "hasDisplay": true
  },
  jup: {
    "id": "jup",
    "name": "Jupiter",
    "category": "tokens",
    "aliases": [
      "jupiter",
      "jup.ag"
    ],
    "tags": [
      "governance",
      "dex",
      "aggregator"
    ],
    "ticker": "JUP",
    "website": "https://jup.ag",
    "mintAddress": "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    "description": "Jupiter is Solana's leading swap and routing layer for discovering liquidity across tokens, perps, and new markets.",
    "relatedIds": [
      "jupsol",
      "jupusd",
      "jupiter-lend",
      "sol"
    ],
    "hasDisplay": true
  },
  phantom: {
    "id": "phantom",
    "name": "Phantom",
    "category": "wallets",
    "aliases": [
      "phantom wallet"
    ],
    "tags": [
      "wallet",
      "browser-extension",
      "mobile"
    ],
    "website": "https://phantom.app",
    "description": "Phantom is a widely used Solana wallet for signing, sending, swapping, and exploring apps, collectibles, and onchain assets.",
    "relatedIds": [
      "sol",
      "jup",
      "magic-eden"
    ],
    "hasDisplay": true
  },
  "helius-orb": {
    "id": "helius-orb",
    "name": "Helius Orb",
    "category": "infrastructure",
    "aliases": [
      "helius-orb",
      "helius orb"
    ],
    "tags": [
      "rpc",
      "api",
      "developer"
    ],
    "website": "https://helius.dev",
    "description": "Orb is Helius' consumer-facing product surface built on top of its Solana RPC and developer infrastructure.",
    "relatedIds": [
      "helius",
      "sol",
      "jup"
    ],
    "hasDisplay": true
  },
  backpack: {
    "id": "backpack",
    "name": "Backpack",
    "category": "wallets",
    "aliases": [
      "backpack wallet",
      "xnft"
    ],
    "tags": [
      "wallet",
      "browser-extension",
      "xnft"
    ],
    "website": "https://backpack.app",
    "description": "Backpack is a wallet and product suite focused on simple, secure Solana access across apps, assets, and mobile flows.",
    "relatedIds": [
      "madlads",
      "sol",
      "jup"
    ],
    "hasDisplay": true
  },
  solflare: {
    "id": "solflare",
    "name": "Solflare",
    "category": "wallets",
    "aliases": [
      "solflare wallet"
    ],
    "tags": [
      "wallet",
      "browser-extension",
      "mobile"
    ],
    "website": "https://solflare.com",
    "description": "Solflare is a long-standing Solana wallet for staking, swaps, portfolio access, and secure account management across devices.",
    "relatedIds": [
      "sol",
      "jup",
      "phantom"
    ],
    "hasDisplay": true
  },
  "sanctum-gateway": {
    "id": "sanctum-gateway",
    "name": "Sanctum Gateway",
    "category": "defi",
    "aliases": [
      "sanctum-gateway"
    ],
    "tags": [
      "liquid-staking",
      "gateway"
    ],
    "website": "https://sanctum.so",
    "description": "Sanctum Gateway is the routing layer that unifies liquidity and swaps across every Sanctum liquid staking token.",
    "relatedIds": [
      "sanctum",
      "infsol",
      "jitosol"
    ],
    "hasDisplay": true
  },
  perena: {
    "id": "perena",
    "name": "Perena",
    "category": "defi",
    "aliases": [
      "perena"
    ],
    "tags": [
      "stablecoin",
      "amm",
      "liquidity"
    ],
    "website": "https://perena.org",
    "description": "Perena is a Solana stablecoin liquidity protocol building deep pools and yield rails for the stablecoin economy.",
    "relatedIds": [
      "usdc",
      "usdt",
      "usd-star"
    ],
    "hasDisplay": true
  },
  superteam: {
    "id": "superteam",
    "name": "Superteam",
    "category": "infrastructure",
    "aliases": [
      "superteam"
    ],
    "tags": [
      "dao",
      "ecosystem",
      "community"
    ],
    "website": "https://superteam.fun",
    "description": "Superteam helps founders, operators, and creators contribute to Solana through programs, bounties, education, and support.",
    "relatedIds": [
      "colosseum",
      "sol",
      "sendai"
    ],
    "hasDisplay": true
  },
  carrot: {
    "id": "carrot",
    "name": "Carrot",
    "category": "defi",
    "aliases": [
      "carrot"
    ],
    "tags": [
      "yield",
      "liquid-staking"
    ],
    "website": "https://carrot.so",
    "description": "Carrot is a yield-bearing product on Solana that allocates deposits across curated onchain yield strategies.",
    "relatedIds": [
      "jitosol",
      "marinade",
      "jup"
    ],
    "hasDisplay": true
  },
  oro: {
    "id": "oro",
    "name": "Oro",
    "category": "tokens",
    "aliases": [
      "oro"
    ],
    "tags": [
      "defi"
    ],
    "ticker": "ORO",
    "website": "https://oro.so",
    "description": "Oro is a Solana-native product for tokenized gold, offering onchain exposure to the physical metal.",
    "relatedIds": [
      "jup",
      "usdc",
      "sol"
    ],
    "hasDisplay": true
  },
  altitude: {
    "id": "altitude",
    "name": "Altitude",
    "category": "defi",
    "aliases": [
      "altitude"
    ],
    "tags": [
      "defi",
      "yield"
    ],
    "website": "https://altitude.fi",
    "description": "Altitude is a Solana-native yield protocol for looped staking and leveraged liquid staking strategies.",
    "relatedIds": [
      "jup",
      "kamino",
      "marinade"
    ],
    "hasDisplay": true
  },
  dflow: {
    "id": "dflow",
    "name": "DFlow",
    "category": "defi",
    "aliases": [
      "dflow"
    ],
    "tags": [
      "dex",
      "order-flow",
      "payments"
    ],
    "website": "https://dflow.net",
    "description": "DFlow is an order flow marketplace connecting wallets and apps to execution venues with price improvement.",
    "relatedIds": [
      "jup",
      "phantom",
      "sol"
    ],
    "hasDisplay": true
  },
  "pump-fun": {
    "id": "pump-fun",
    "name": "Pump.fun",
    "category": "infrastructure",
    "aliases": [
      "pump",
      "pump.fun"
    ],
    "tags": [
      "token-launch",
      "meme",
      "launchpad"
    ],
    "website": "https://pump.fun",
    "description": "Pump.fun is a consumer launch surface for discovering and trading fast-moving, community-driven tokens on Solana.",
    "relatedIds": [
      "bonk",
      "moonshot",
      "sol"
    ],
    "hasDisplay": true
  },
  "usd-prime": {
    "id": "usd-prime",
    "name": "USD Prime",
    "category": "tokens",
    "aliases": [
      "usd-prime",
      "usdprime"
    ],
    "tags": [
      "stablecoin"
    ],
    "ticker": "USDPrime",
    "description": "USD Prime is a Solana-native stablecoin designed for institutional flows and deep onchain liquidity.",
    "relatedIds": [
      "usdc",
      "usdt",
      "perena"
    ],
    "hasDisplay": true
  },
  fuse: {
    "id": "fuse",
    "name": "Fuse",
    "category": "defi",
    "aliases": [
      "fuse"
    ],
    "tags": [
      "defi",
      "yield",
      "restaking"
    ],
    "website": "https://fuse.fi",
    "description": "Fuse is a Solana restaking and yield protocol enabling new security and reward primitives on top of existing LSTs.",
    "relatedIds": [
      "sol",
      "jito",
      "marinade"
    ],
    "hasDisplay": true
  },
  "usd-star": {
    "id": "usd-star",
    "name": "USD STAR",
    "category": "tokens",
    "aliases": [
      "usd-star",
      "usdstar"
    ],
    "tags": [
      "stablecoin"
    ],
    "ticker": "USD★",
    "description": "USD★ is a yield-bearing stablecoin on Solana designed to pass native onchain returns directly to holders.",
    "relatedIds": [
      "perena",
      "usdc",
      "usdt"
    ],
    "hasDisplay": true
  },
  xstock: {
    "id": "xstock",
    "name": "xStock",
    "category": "defi",
    "aliases": [
      "xstock"
    ],
    "tags": [
      "stocks",
      "tokenized",
      "trading"
    ],
    "website": "https://xstock.io",
    "description": "xStock brings tokenized public equities onchain, letting Solana users access stock exposure around the clock.",
    "relatedIds": [
      "usdc",
      "jup",
      "sol"
    ],
    "hasDisplay": true
  },
  "magic-eden": {
    "id": "magic-eden",
    "name": "Magic Eden",
    "category": "nft",
    "aliases": [
      "magic eden",
      "me"
    ],
    "tags": [
      "marketplace",
      "nft",
      "trading"
    ],
    "website": "https://magiceden.io",
    "description": "Magic Eden is a consumer marketplace and launch platform for collectibles, creators, and community-led digital products.",
    "relatedIds": [
      "madlads",
      "claynosaurz",
      "phantom"
    ],
    "hasDisplay": true
  },
  colosseum: {
    "id": "colosseum",
    "name": "Colosseum",
    "category": "infrastructure",
    "aliases": [
      "colosseum"
    ],
    "tags": [
      "hackathon",
      "grants",
      "ecosystem"
    ],
    "website": "https://colosseum.org",
    "description": "Colosseum runs Solana's flagship hackathons and helps winning teams grow into funded startups.",
    "relatedIds": [
      "superteam",
      "sol",
      "sendai"
    ],
    "hasDisplay": true
  },
  scloud: {
    "id": "scloud",
    "name": "sCLOUD",
    "category": "tokens",
    "aliases": [
      "scloud",
      "sanctum-cloud"
    ],
    "tags": [
      "liquid-staking",
      "staking"
    ],
    "website": "https://sanctum.so",
    "description": "sCLOUD is Sanctum's liquid-staked version of CLOUD, earning staking rewards while remaining usable across Solana DeFi.",
    "relatedIds": [
      "sanctum",
      "infsol",
      "sol"
    ],
    "hasDisplay": true
  },
  crossmint: {
    "id": "crossmint",
    "name": "Crossmint",
    "category": "infrastructure",
    "aliases": [
      "crossmint"
    ],
    "tags": [
      "nft",
      "api",
      "developer"
    ],
    "website": "https://crossmint.com",
    "description": "Crossmint provides developer infrastructure for onboarding users, minting NFTs, and accepting payments across chains.",
    "relatedIds": [
      "sol",
      "phantom",
      "magic-eden"
    ],
    "hasDisplay": true
  },
  marginfi: {
    "id": "marginfi",
    "name": "MarginFi",
    "category": "defi",
    "aliases": [
      "marginfi",
      "margin.fi"
    ],
    "tags": [
      "lending",
      "margin",
      "leverage"
    ],
    "website": "https://marginfi.com",
    "description": "MarginFi is a Solana lending and borrowing protocol offering overcollateralized markets and leveraged strategies.",
    "relatedIds": [
      "kamino",
      "jup",
      "marinade"
    ],
    "hasDisplay": true
  },
  kamino: {
    "id": "kamino",
    "name": "Kamino Finance",
    "category": "defi",
    "aliases": [
      "kamino"
    ],
    "tags": [
      "yield",
      "lending",
      "liquidity"
    ],
    "website": "https://kamino.finance",
    "description": "Kamino is a Solana DeFi platform for lending, vaults, leverage, and capital-efficient yield strategies.",
    "relatedIds": [
      "marginfi",
      "jup",
      "marinade"
    ],
    "hasDisplay": true
  },
  infsol: {
    "id": "infsol",
    "name": "infSOL",
    "category": "tokens",
    "aliases": [
      "infsol",
      "infinite-sol"
    ],
    "tags": [
      "liquid-staking",
      "staking"
    ],
    "website": "https://sanctum.so",
    "description": "infSOL is a basket liquid staking token from Sanctum Infinity, routing stake across many validators for diversified yield.",
    "relatedIds": [
      "sanctum",
      "jitosol",
      "sol"
    ],
    "hasDisplay": true
  },
  moonshot: {
    "id": "moonshot",
    "name": "Moonshot",
    "category": "infrastructure",
    "aliases": [
      "moonshot"
    ],
    "tags": [
      "token-launch",
      "launchpad"
    ],
    "website": "https://moonshot.money",
    "description": "Moonshot is a consumer mobile app for buying, selling, and launching tokens on Solana.",
    "relatedIds": [
      "pump-fun",
      "bonk",
      "sol"
    ],
    "hasDisplay": true
  },
  umbra: {
    "id": "umbra",
    "name": "Umbra",
    "category": "defi",
    "aliases": [
      "umbra"
    ],
    "tags": [
      "privacy",
      "stealth",
      "defi"
    ],
    "website": "https://umbra.cash",
    "description": "Umbra brings private, stealth-address-style transactions to Solana for confidential payments and flows.",
    "relatedIds": [
      "sol",
      "jup",
      "arcium"
    ],
    "hasDisplay": true
  },
  arcium: {
    "id": "arcium",
    "name": "Arcium",
    "category": "infrastructure",
    "aliases": [
      "arcium"
    ],
    "tags": [
      "privacy",
      "mpc",
      "confidential-computing"
    ],
    "website": "https://arcium.com",
    "description": "Arcium is a confidential computing network enabling encrypted compute and MPC-based privacy for Solana apps.",
    "relatedIds": [
      "sol",
      "helius",
      "umbra"
    ],
    "hasDisplay": true
  },
  bonk: {
    "id": "bonk",
    "name": "BONK",
    "category": "tokens",
    "aliases": [
      "bonk"
    ],
    "tags": [
      "meme"
    ],
    "ticker": "BONK",
    "website": "https://bonkcoin.com",
    "mintAddress": "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    "description": "BONK is Solana's original community meme coin, widely distributed across the network's users, apps, and ecosystem.",
    "relatedIds": [
      "pump-fun",
      "jup",
      "moonshot"
    ],
    "hasDisplay": true
  },
  kast: {
    "id": "kast",
    "name": "Kast",
    "category": "defi",
    "aliases": [
      "kast"
    ],
    "tags": [
      "debit-card",
      "payments",
      "defi"
    ],
    "website": "https://kast.app",
    "description": "Kast is a stablecoin-powered debit card and spending app for everyday payments onchain.",
    "relatedIds": [
      "sol",
      "usdc",
      "moonpay"
    ],
    "hasDisplay": true
  },
  asgard: {
    "id": "asgard",
    "name": "Asgard",
    "category": "defi",
    "aliases": [
      "asgard"
    ],
    "tags": [
      "defi",
      "yield"
    ],
    "website": "https://asgard.finance",
    "description": "Asgard is a Solana yield and structured product platform for onchain capital strategies.",
    "relatedIds": [
      "jup",
      "sol",
      "kamino"
    ],
    "hasDisplay": true
  },
  fomo: {
    "id": "fomo",
    "name": "FOMO",
    "category": "defi",
    "aliases": [
      "fomo"
    ],
    "tags": [
      "defi",
      "trading"
    ],
    "website": "https://fomo.fund",
    "description": "FOMO is a Solana social trading platform focused on live markets and community-driven discovery.",
    "relatedIds": [
      "sol",
      "jup",
      "bonk"
    ],
    "hasDisplay": true
  },
  "jupiter-lend": {
    "id": "jupiter-lend",
    "name": "Jupiter Lend",
    "category": "defi",
    "aliases": [
      "jupiter-lend",
      "jup-lend"
    ],
    "tags": [
      "lending",
      "borrowing",
      "jupiter"
    ],
    "website": "https://jup.ag",
    "description": "Jupiter Lend is Jupiter's lending market for borrowing and earning against major Solana assets.",
    "relatedIds": [
      "jup",
      "jupsol",
      "jupusd"
    ],
    "hasDisplay": true
  },
  moonpay: {
    "id": "moonpay",
    "name": "MoonPay",
    "category": "infrastructure",
    "aliases": [
      "moonpay"
    ],
    "tags": [
      "payments",
      "onramp",
      "fiat"
    ],
    "website": "https://moonpay.com",
    "description": "MoonPay connects users to digital assets through payments, onboarding, and checkout experiences across crypto products.",
    "relatedIds": [
      "usdc",
      "sol",
      "phantom"
    ],
    "hasDisplay": true
  },
  jto: {
    "id": "jto",
    "name": "Jito",
    "category": "tokens",
    "aliases": [
      "jito"
    ],
    "tags": [
      "governance",
      "liquid-staking"
    ],
    "ticker": "JTO",
    "website": "https://jito.network",
    "mintAddress": "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
    "description": "JTO is the governance token of Jito, coordinating decisions across Jito's staking and MEV infrastructure on Solana.",
    "relatedIds": [
      "jito",
      "jitosol",
      "sol"
    ],
    "hasDisplay": true
  },
  sendai: {
    "id": "sendai",
    "name": "SendAI",
    "category": "infrastructure",
    "aliases": [
      "sendai"
    ],
    "tags": [
      "ai",
      "automation",
      "infrastructure"
    ],
    "website": "https://sendai.fun",
    "description": "SendAI builds AI-native tooling and agent infrastructure for the Solana ecosystem.",
    "relatedIds": [
      "superteam",
      "colosseum",
      "helius"
    ],
    "hasDisplay": true
  },
  eurc: {
    "id": "eurc",
    "name": "EURC",
    "category": "tokens",
    "aliases": [
      "eurc"
    ],
    "tags": [
      "stablecoin",
      "euro"
    ],
    "ticker": "EURC",
    "website": "https://www.circle.com/eurc",
    "mintAddress": "HzwqbKZw8HxMN6bF2yFZNrht3c2iXXzpKcFu7uBEDKtr",
    "description": "EURC is Circle's euro-denominated stablecoin, fully reserved and issued onchain for payments and trading.",
    "relatedIds": [
      "usdc",
      "circle",
      "usdt"
    ],
    "hasDisplay": true
  },
  usdc: {
    "id": "usdc",
    "name": "USDC",
    "category": "tokens",
    "aliases": [
      "usdc",
      "usd-coin"
    ],
    "tags": [
      "stablecoin"
    ],
    "ticker": "USDC",
    "website": "https://www.circle.com/usdc",
    "mintAddress": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    "description": "USDC is Circle's fully reserved US dollar stablecoin and the most widely used dollar-backed asset on Solana.",
    "relatedIds": [
      "usdt",
      "sol",
      "jup"
    ],
    "hasDisplay": true
  },
  circle: {
    "id": "circle",
    "name": "Circle",
    "category": "infrastructure",
    "aliases": [
      "circle"
    ],
    "tags": [
      "stablecoin",
      "payments",
      "infrastructure"
    ],
    "website": "https://www.circle.com",
    "description": "Circle issues USDC and EURC, providing stablecoin infrastructure and payments rails across major blockchains including Solana.",
    "relatedIds": [
      "usdc",
      "eurc",
      "sol"
    ],
    "hasDisplay": true
  },
  bags: {
    "id": "bags",
    "name": "Bags",
    "category": "defi",
    "aliases": [
      "bags"
    ],
    "tags": [
      "defi",
      "portfolio"
    ],
    "website": "https://bags.fm",
    "description": "Bags is a Solana social wallet and portfolio experience built around shared onchain discovery.",
    "relatedIds": [
      "jup",
      "sol",
      "phantom"
    ],
    "hasDisplay": true
  },
  "powered-by-solana": {
    "id": "powered-by-solana",
    "name": "Powered by Solana",
    "category": "infrastructure",
    "aliases": [
      "powered-by-solana"
    ],
    "tags": [
      "branding",
      "ecosystem",
      "solana"
    ],
    "description": "The 'Powered by Solana' mark identifies products and apps built on the Solana network.",
    "relatedIds": [
      "sol",
      "opos",
      "superteam"
    ],
    "hasDisplay": true
  },
  jupusd: {
    "id": "jupusd",
    "name": "JupUSD",
    "category": "tokens",
    "aliases": [
      "jupusd"
    ],
    "tags": [
      "stablecoin",
      "jupiter"
    ],
    "ticker": "JupUSD",
    "website": "https://jup.ag",
    "mintAddress": "JUPUSDC8NZHaUKKJUBeFMh2h3N2Y7ACCHpkKfpHjuAN",
    "description": "JupUSD is Jupiter's US dollar stablecoin, integrated directly into Jupiter's routing and trading surfaces.",
    "relatedIds": [
      "jup",
      "jupsol",
      "usdc"
    ],
    "hasDisplay": true
  },
  jitosol: {
    "id": "jitosol",
    "name": "Jito Staked SOL",
    "category": "tokens",
    "aliases": [
      "jitosol",
      "jito-staked-sol"
    ],
    "tags": [
      "liquid-staking",
      "defi"
    ],
    "ticker": "JitoSOL",
    "website": "https://jito.network",
    "mintAddress": "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn",
    "description": "JitoSOL is the Jito liquid staking token, representing SOL staked with MEV-optimized validator operations.",
    "relatedIds": [
      "jito",
      "jto",
      "sol"
    ],
    "hasDisplay": true
  },
  madlads: {
    "id": "madlads",
    "name": "Madlads",
    "category": "nft",
    "aliases": [
      "madlads",
      "mad-lads"
    ],
    "tags": [
      "nft",
      "collection",
      "backpack"
    ],
    "website": "https://madlads.com",
    "description": "Mad Lads is a flagship Solana NFT collection closely tied to the Backpack wallet and xNFT ecosystem.",
    "relatedIds": [
      "backpack",
      "magic-eden",
      "claynosaurz"
    ],
    "hasDisplay": true
  },
  opos: {
    "id": "opos",
    "name": "OPOS",
    "category": "infrastructure",
    "aliases": [
      "opos",
      "only-possible-on-solana"
    ],
    "tags": [
      "branding",
      "ecosystem",
      "solana"
    ],
    "description": "The 'Only Possible On Solana' mark celebrates products and moments that showcase Solana's unique capabilities.",
    "relatedIds": [
      "sol",
      "powered-by-solana",
      "superteam"
    ],
    "hasDisplay": true
  },
  "drip-haus": {
    "id": "drip-haus",
    "name": "Drip Haus",
    "category": "nft",
    "aliases": [
      "drip-haus",
      "drip"
    ],
    "tags": [
      "nft",
      "creator",
      "drops"
    ],
    "website": "https://drip.haus",
    "description": "Drip Haus is a Solana creator platform distributing free collectible drops to engaged audiences.",
    "relatedIds": [
      "magic-eden",
      "madlads",
      "metaplex"
    ],
    "hasDisplay": true
  },
  jupsol: {
    "id": "jupsol",
    "name": "JupSOL",
    "category": "tokens",
    "aliases": [
      "jupsol",
      "jupiter-staked-sol"
    ],
    "tags": [
      "liquid-staking",
      "jupiter"
    ],
    "ticker": "JupSOL",
    "website": "https://jup.ag",
    "mintAddress": "jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v",
    "description": "JupSOL is Jupiter's liquid staking token, routing SOL stake through high-performance validator operations.",
    "relatedIds": [
      "jup",
      "jupusd",
      "sol"
    ],
    "hasDisplay": true
  },
  metadao: {
    "id": "metadao",
    "name": "MetaDAO",
    "category": "infrastructure",
    "aliases": [
      "metadao",
      "meta-dao"
    ],
    "tags": [
      "dao",
      "governance"
    ],
    "website": "https://metadao.fi",
    "description": "MetaDAO is a futarchy-based governance system using onchain prediction markets to make decisions.",
    "relatedIds": [
      "sol",
      "superteam",
      "jup"
    ],
    "hasDisplay": true
  },
  meteora: {
    "id": "meteora",
    "name": "Meteora",
    "category": "defi",
    "aliases": [
      "meteora"
    ],
    "tags": [
      "liquidity",
      "amm",
      "yield"
    ],
    "website": "https://meteora.ag",
    "description": "Meteora is a Solana liquidity platform offering dynamic pools and capital-efficient market-making primitives.",
    "relatedIds": [
      "jup",
      "raydium",
      "kamino"
    ],
    "hasDisplay": true
  },
  jito: {
    "id": "jito",
    "name": "Jito",
    "category": "defi",
    "aliases": [
      "jito"
    ],
    "tags": [
      "liquid-staking",
      "mev"
    ],
    "website": "https://jito.network",
    "description": "Jito builds validator and MEV infrastructure designed to make Solana execution more efficient, performant, and aligned.",
    "relatedIds": [
      "jitosol",
      "jto",
      "sol"
    ],
    "hasDisplay": true
  },
  marinade: {
    "id": "marinade",
    "name": "Marinade",
    "category": "defi",
    "aliases": [
      "marinade"
    ],
    "tags": [
      "liquid-staking",
      "defi"
    ],
    "website": "https://marinade.finance",
    "description": "Marinade is a Solana liquid staking protocol issuing mSOL and coordinating stake across a diverse, decentralized validator set.",
    "relatedIds": [
      "jito",
      "jitosol",
      "sanctum"
    ],
    "hasDisplay": true
  },
  metaplex: {
    "id": "metaplex",
    "name": "Metaplex",
    "category": "nft",
    "aliases": [
      "metaplex"
    ],
    "tags": [
      "nft",
      "standard",
      "infrastructure"
    ],
    "website": "https://metaplex.com",
    "description": "Metaplex provides Solana standards and tooling for minting, managing, and distributing digital assets and collectibles.",
    "relatedIds": [
      "magic-eden",
      "madlads",
      "claynosaurz"
    ],
    "hasDisplay": true
  },
  raydium: {
    "id": "raydium",
    "name": "Raydium",
    "category": "defi",
    "aliases": [
      "raydium"
    ],
    "tags": [
      "dex",
      "amm"
    ],
    "website": "https://raydium.io",
    "description": "Raydium is a Solana liquidity venue for swaps, pools, launches, and active market participation across the ecosystem.",
    "relatedIds": [
      "jup",
      "meteora",
      "sol"
    ],
    "hasDisplay": true
  },
  zora: {
    "id": "zora",
    "name": "Zora",
    "category": "nft",
    "aliases": [
      "zora"
    ],
    "tags": [
      "marketplace",
      "nft",
      "creator"
    ],
    "website": "https://zora.co",
    "description": "Zora is a creator protocol for minting, trading, and distributing media as onchain digital objects.",
    "relatedIds": [
      "magic-eden",
      "metaplex",
      "crossmint"
    ],
    "hasDisplay": true
  },
  claynosaurz: {
    "id": "claynosaurz",
    "name": "Claynosaurz",
    "category": "nft",
    "aliases": [
      "claynosaurz"
    ],
    "tags": [
      "nft",
      "collection"
    ],
    "website": "https://claynosaurz.com",
    "description": "Claynosaurz is a narrative-driven Solana NFT collection and animation studio building original IP onchain.",
    "relatedIds": [
      "magic-eden",
      "madlads",
      "metaplex"
    ],
    "hasDisplay": true
  },
  seeker: {
    "id": "seeker",
    "name": "Seeker",
    "category": "wallets",
    "aliases": [
      "seeker",
      "solana-seeker"
    ],
    "tags": [
      "wallet",
      "mobile",
      "hardware"
    ],
    "website": "https://solanamobile.com",
    "description": "Seeker is Solana Mobile's crypto-native smartphone, shipping with wallet access and deep app integrations.",
    "relatedIds": [
      "phantom",
      "backpack",
      "solflare"
    ],
    "hasDisplay": true
  },
  avici: {
    "id": "avici",
    "name": "Avici",
    "category": "defi",
    "aliases": [
      "avici"
    ],
    "tags": [
      "defi"
    ],
    "website": "https://avici.io",
    "description": "Avici is a Solana DeFi product focused on capital-efficient onchain strategies.",
    "relatedIds": [
      "jup",
      "sol",
      "kamino"
    ],
    "hasDisplay": true
  },
  squads: {
    "id": "squads",
    "name": "Squads",
    "category": "infrastructure",
    "aliases": [
      "squads",
      "squads-protocol"
    ],
    "tags": [
      "multisig",
      "treasury",
      "governance"
    ],
    "website": "https://squads.so",
    "description": "Squads builds multi-signature and treasury tooling that helps teams manage permissions, assets, and operational workflows.",
    "relatedIds": [
      "sol",
      "phantom",
      "marginfi"
    ],
    "hasDisplay": true
  },
  usdt: {
    "id": "usdt",
    "name": "USDT",
    "category": "tokens",
    "aliases": [
      "usdt",
      "tether"
    ],
    "tags": [
      "stablecoin"
    ],
    "ticker": "USDT",
    "website": "https://tether.to",
    "mintAddress": "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    "description": "USDT is Tether's US dollar stablecoin, the largest dollar-denominated crypto asset, available on Solana.",
    "relatedIds": [
      "usdc",
      "sol",
      "jup"
    ],
    "hasDisplay": true
  },
  cloud: {
    "id": "cloud",
    "name": "Sanctum",
    "category": "tokens",
    "aliases": [
      "sanctum"
    ],
    "tags": [
      "governance",
      "liquid-staking"
    ],
    "ticker": "CLOUD",
    "mintAddress": "CLoUDKc4Ane7HeQcPpE3YHnznRxhMimJ4MyaUqyHFzAu",
    "hasDisplay": false
  },
  drift: {
    "id": "drift",
    "name": "Drift Protocol",
    "category": "defi",
    "aliases": [
      "drift"
    ],
    "tags": [
      "perps",
      "derivatives",
      "margin"
    ],
    "website": "https://drift.trade",
    "hasDisplay": false
  },
  "helium-protocol": {
    "id": "helium-protocol",
    "name": "Helium",
    "category": "infrastructure",
    "aliases": [
      "helium",
      "helium network"
    ],
    "tags": [
      "depin",
      "iot",
      "wireless"
    ],
    "website": "https://helium.com",
    "hasDisplay": false
  },
  hnt: {
    "id": "hnt",
    "name": "Helium",
    "category": "tokens",
    "aliases": [
      "helium"
    ],
    "tags": [
      "depin",
      "iot"
    ],
    "ticker": "HNT",
    "mintAddress": "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux",
    "hasDisplay": false
  },
  "jupiter-protocol": {
    "id": "jupiter-protocol",
    "name": "Jupiter",
    "category": "defi",
    "aliases": [
      "jup",
      "jup.ag",
      "jupiter aggregator"
    ],
    "tags": [
      "dex",
      "aggregator",
      "perps"
    ],
    "website": "https://jup.ag",
    "hasDisplay": false
  },
  lifinity: {
    "id": "lifinity",
    "name": "Lifinity",
    "category": "defi",
    "aliases": [
      "lifinity"
    ],
    "tags": [
      "dex",
      "amm",
      "proactive-market-making"
    ],
    "website": "https://lifinity.io",
    "hasDisplay": false
  },
  mango: {
    "id": "mango",
    "name": "Mango Markets",
    "category": "defi",
    "aliases": [
      "mango",
      "mango markets"
    ],
    "tags": [
      "margin",
      "perps",
      "trading"
    ],
    "website": "https://mango.markets",
    "hasDisplay": false
  },
  mayan: {
    "id": "mayan",
    "name": "Mayan Finance",
    "category": "infrastructure",
    "aliases": [
      "mayan"
    ],
    "tags": [
      "bridge",
      "cross-chain",
      "swap"
    ],
    "website": "https://mayan.finance",
    "hasDisplay": false
  },
  msol: {
    "id": "msol",
    "name": "Marinade Staked SOL",
    "category": "tokens",
    "aliases": [
      "marinade-staked-sol"
    ],
    "tags": [
      "liquid-staking",
      "defi"
    ],
    "ticker": "mSOL",
    "mintAddress": "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So",
    "hasDisplay": false
  },
  orca: {
    "id": "orca",
    "name": "Orca",
    "category": "defi",
    "aliases": [
      "orca dex",
      "whirlpool"
    ],
    "tags": [
      "dex",
      "amm",
      "concentrated-liquidity"
    ],
    "website": "https://orca.so",
    "hasDisplay": false
  },
  pengu: {
    "id": "pengu",
    "name": "Pudgy Penguins",
    "category": "tokens",
    "aliases": [
      "pudgy-penguins",
      "pengu"
    ],
    "tags": [
      "meme",
      "nft"
    ],
    "ticker": "PENGU",
    "mintAddress": "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv",
    "hasDisplay": false
  },
  phoenix: {
    "id": "phoenix",
    "name": "Phoenix",
    "category": "defi",
    "aliases": [
      "phoenix",
      "phoenix protocol"
    ],
    "tags": [
      "clob",
      "orderbook",
      "dex"
    ],
    "website": "https://phoenix.trade",
    "hasDisplay": false
  },
  pyth: {
    "id": "pyth",
    "name": "Pyth Network",
    "category": "tokens",
    "aliases": [
      "pyth",
      "pyth-network"
    ],
    "tags": [
      "oracle",
      "infrastructure"
    ],
    "ticker": "PYTH",
    "mintAddress": "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
    "hasDisplay": false
  },
  ray: {
    "id": "ray",
    "name": "Raydium",
    "category": "tokens",
    "aliases": [
      "raydium"
    ],
    "tags": [
      "governance",
      "dex",
      "amm"
    ],
    "ticker": "RAY",
    "mintAddress": "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    "hasDisplay": false
  },
  realms: {
    "id": "realms",
    "name": "Realms",
    "category": "infrastructure",
    "aliases": [
      "realms",
      "spl-governance"
    ],
    "tags": [
      "dao",
      "governance"
    ],
    "website": "https://realms.today",
    "hasDisplay": false
  },
  solend: {
    "id": "solend",
    "name": "Solend",
    "category": "defi",
    "aliases": [
      "solend"
    ],
    "tags": [
      "lending",
      "borrowing"
    ],
    "website": "https://solend.fi",
    "hasDisplay": false
  },
  "step-finance": {
    "id": "step-finance",
    "name": "Step Finance",
    "category": "infrastructure",
    "aliases": [
      "step"
    ],
    "tags": [
      "portfolio",
      "dashboard",
      "analytics"
    ],
    "website": "https://step.finance",
    "hasDisplay": false
  },
  tensor: {
    "id": "tensor",
    "name": "Tensor",
    "category": "nft",
    "aliases": [
      "tensor",
      "tensor.trade"
    ],
    "tags": [
      "marketplace",
      "nft",
      "defi",
      "amm"
    ],
    "website": "https://tensor.trade",
    "hasDisplay": false
  },
  w: {
    "id": "w",
    "name": "Wormhole",
    "category": "tokens",
    "aliases": [
      "wormhole"
    ],
    "tags": [
      "bridge",
      "interoperability"
    ],
    "ticker": "W",
    "mintAddress": "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ",
    "hasDisplay": false
  },
  wormhole: {
    "id": "wormhole",
    "name": "Wormhole",
    "category": "infrastructure",
    "aliases": [
      "wormhole bridge"
    ],
    "tags": [
      "bridge",
      "interoperability",
      "cross-chain"
    ],
    "website": "https://wormhole.com",
    "hasDisplay": false
  },
};
